apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ha-matrix-bot.fullname" . }}-store
  labels:
    {{- include "ha-matrix-bot.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- with .Values.persistence.store.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.store.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ha-matrix-bot.fullname" . }}-data
  labels:
    {{- include "ha-matrix-bot.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- with .Values.persistence.data.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
