{{- if and (not .Values.secrets.existingSecret) .Values.secrets.values }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ha-matrix-bot.fullname" . }}
  labels:
    {{- include "ha-matrix-bot.labels" . | nindent 4 }}
stringData:
  {{- range $key, $value := .Values.secrets.values }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
